dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - cycler
    - kiwisolver
    - matplotlib
    - numpy
    - pandas
    - pyparsing
    - python-dateutil
    - pytz
    - scikit-learn
    - scipy
    - seaborn
    - setuptools
    - six
   
